Homework 36
palesya/JavaTeachMeSkills_AlesyaPesetskaya pull request #26
Opened 2022-08-16 20:07 UTC by palesya

2022-08-21 17:49 UTC, gr00shik requested changes
отлично

2022-08-21 17:49 UTC, gr00shik commented on homework_34/src/main/java/com/tms/springboot/controller/FileController.java
> +    FileCreationService service;
модификатор доступа

2022-08-21 17:49 UTC, gr00shik commented on homework_34/src/main/java/com/tms/springboot/controller/FileController.java
> +    public void addCounterToFile() throws IOException {
а что это за бин?

2022-08-21 17:49 UTC, gr00shik commented on homework_34/src/main/java/com/tms/springboot/files/dev.txt
> +
не стоит файлы которые создаются при запуске ложить в ПР

2022-08-21 17:49 UTC, gr00shik commented on homework_34/src/main/java/com/tms/springboot/service/FileCreationService.java
> +    private int getLastIndex(Path path) throws IOException {
предполагалось просто перезаписывать счетчик - так тоже нормально

2022-08-21 17:49 UTC, gr00shik commented on homework_34/src/main/resources/application.yaml
> +spring:
странно что в yaml тут нет ошибки, так как у тебя две проперти имеют один префикс

2022-08-21 17:49 UTC, gr00shik commented on homework_35/src/main/java/com/tms/hibernate/model/Car.java
> +        return Objects.hash(id, number, brand, dateProduced, created, updated, available, version, client, regions);
не стоит включать служебные поля а хеш-код и equals

2022-08-31 10:27 UTC, palesya commented on homework_35/src/main/java/com/tms/hibernate/model/Car.java
> +        return Objects.hash(id, number, brand, dateProduced, created, updated, available, version, client, regions);
removed

2022-08-31 10:28 UTC, palesya commented on homework_34/src/main/resources/application.yaml
> +spring:
одни и те же свойства могут храниться, если они разделены тремя пробелами

2022-08-31 10:31 UTC, palesya commented on homework_34/src/main/java/com/tms/springboot/files/dev.txt
> +
removed

2022-08-31 10:31 UTC, palesya commented on homework_34/src/main/java/com/tms/springboot/controller/FileController.java
> +    public void addCounterToFile() throws IOException {
для добавления счётчика

2022-08-31 10:32 UTC, palesya commented on homework_34/src/main/java/com/tms/springboot/controller/FileController.java
> +    FileCreationService service;
private

2022-08-31 10:33 UTC, merged